### ISSUE TITLE
Provision Transaction Layer PostgreSQL database

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/oasis-indexer#3]
**Goal**

Create a PostgreSQL database and related infrastructure. This should be under `production`.

**Tasks**:

- [ ] Create vault app provision for indexer database credentials
- [ ] Create Postgres roles and databases for oasis-block-indexer
- [ ] Add auth_k8s_role_name

**Acceptance**:

- [ ] shell user can log into database with the appropriate credentials
